include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**

linter:
  rules:
    avoid_print: true
    require_trailing_commas: true
    always_declare_return_types: true
    constant_identifier_names: false
    prefer_const_constructors_in_immutables: false
    use_key_in_widget_constructors: false
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
