name: bt_business
description: BT Business project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: 2.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HELPERS AND SERVICES
  intl: ^0.17.0
  logger: ^1.1.0
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  mask_text_input_formatter: ^2.1.0

  # ARCHITECTURE
  auto_route: ^3.2.1
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  # REST
  http: ^0.13.4

  # STORAGE
  flutter_secure_storage: ^5.0.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  shared_preferences: ^2.0.6

  # UI
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  adaptive_theme: ^2.3.0
  otp_text_field: ^1.1.2

dev_dependencies:
  # TESTING
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  auto_route_generator: ^3.2.1

  # SERVICES
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  freezed: ^1.1.0
  hive_generator: ^1.1.2

  # APP ICONS HELPER
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/launcher_icon/
    - assets/mock/
    - assets/icons/

  fonts:
    - family: BTCurveBold
      fonts:
        - asset: fonts/BTCurveBold.ttf
    - family: BTCurveHeadline
      fonts:
        - asset: fonts/BTCurveHeadline.ttf
    - family: BTCurveHeadlineItalic
      fonts:
        - asset: fonts/BTCurveHeadlineItalic.ttf
    - family: BTCurveItalic
      fonts:
        - asset: fonts/BTCurveItalic.ttf
    - family: BTCurveItalicBold
      fonts:
        - asset: fonts/BTCurveItalicBold.ttf
    - family: BTCurveRegular
      fonts:
        - asset: fonts/BTCurveRegular.ttf
#  module:
#    androidPackage: com.bt.business.bt_business.embeded
#    iosBundleIdentifier: com.bt.business.btBusiness.embeded
#    androidX: true

flutter_intl:
  main_locale: en
  enabled: true
